#include "GPIO.h"


void portF_Init(void) 
{

	SYSCTL_RCGCGPIO_R |= 0X20;  //port f clk enable
	while((SYSCTL_PRGPIO_R& 0X20)==0); //delay
	GPIO_PORTF_LOCK_R = GPIO_LOCK_KEY;
	GPIO_PORTF_CR_R |= 0X0E;
	GPIO_PORTF_AMSEL_R &=~ 0X0E;
	GPIO_PORTF_PCTL_R &=~ 0X0000FFF0;
	GPIO_PORTF_AFSEL_R &=~ 0X0E;
	GPIO_PORTF_DIR_R |= 0X0E;
	GPIO_PORTF_DEN_R |= 0X0E;
	GPIO_PORTF_DATA_R &=~0X0E;
 
}


